[package]
name = "arpg-items-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.30.0"
crossterm = "0.29.0"
strum = "0.27.2"


[dependencies.uuid]
version = "1.20.0"
# Lets you generate random UUIDs
features = [
    "v4",
]